---
title: "Programa de Prevenci칩n & Control del Dengue | 2025"
format: 
  dashboard:
      nav-buttons: [twitter, github, facebook]
theme: custom.scss
---

```{r setup}
library(sf)
mapview::mapviewOptions(default = TRUE,
                        basemaps.color.shuffle = FALSE)
if(as.vector(Sys.info()["sysname"]) == "Darwin"){
load("~/OneDrive/proyects/geocoding_mex/2025/8.RData/denmex_2025.RData")
} else if(as.vector(Sys.info()["sysname"]) == "Windows"){
   load("D:\\OneDrive\\proyects\\geocoding_mex\\2024\\8.RData\\denmex_2024.RData")
} else if(as.vector(Sys.info()["sysname"]) == "Linux"){
    
}
library(magrittr)
```



# [**Cadenas de Transmisi칩n**]{style="font-size:8pt"}

::: panel-tabset

### [**Culiacan**]{style="color:#990000"}

```{r chains_culiacan}
z <- z |>
    dplyr::filter(accuracy != "locality")
    
denhotspots::transmission_chains_map(geocoded_dataset = z,
                                     cve_edo = "25",
                                     locality = "Culiacan Rosales",
                                     dengue_cases = "Confirmado")
```


### [**Mazatlan**]{style="color:#990000"}

```{r chains_mazatlan}
z <- z |>
    dplyr::filter(accuracy != "locality")
    

denhotspots::transmission_chains_map(geocoded_dataset = z,
                                     cve_edo = "25",
                                     locality = "Mazatlan",
                                     dengue_cases = "Probable")
```


:::


# [**Mapas de Calor**]{style="font-size:8pt"}

::: panel-tabset

### [**Culiacan**]{style="color:#990000"}

```{r heatmap_culiacan}

z <- z |>
    dplyr::filter(accuracy != "locality")
    


densnv::mp_heatmap(geocoded_datasets = z,
                   cve_edo = "25",
                   locality = "Culiacan de Rosales",
                   status_caso = c(1, 2),
                   week = c(1:53),
                   zoom = NULL,
                   map_type = NULL,
                   alpha = 0.6,
                   static = FALSE,
                   palette = viridis::turbo)
```



### [**Mazatl치n**]{style="color:#990000"}

```{r heatmap_mazatlan}

z <- z |>
    dplyr::filter(accuracy != "locality")
    

densnv::mp_heatmap(geocoded_datasets = z,
                   cve_edo = "25",
                   locality = "Mazatl치n",
                   status_caso = c(1, 2),
                   week = c(1:53),
                   zoom = NULL,
                   map_type = NULL,
                   alpha = 0.6,
                   static = FALSE,
                   palette = viridis::turbo)
```

### [**Los Mochis**]{style="color:#990000"}

```{r heatmap_mochis}

z <- z |>
    dplyr::filter(accuracy != "locality")
    

densnv::mp_heatmap(geocoded_datasets = z,
                   cve_edo = "25",
                   locality = "Los Mochis",
                   status_caso = c(1, 2),
                   week = c(1:53),
                   zoom = NULL,
                   map_type = NULL,
                   alpha = 0.6,
                   static = FALSE,
                   palette = viridis::turbo)
```


### [**Guasave**]{style="color:#990000"}

```{r heatmap_guasave}

z <- z |>
    dplyr::filter(accuracy != "locality")
    

densnv::mp_heatmap(geocoded_datasets = z,
                   cve_edo = "25",
                   locality = "Guasave",
                   status_caso = c(1, 2),
                   week = c(1:53),
                   zoom = NULL,
                   map_type = NULL,
                   alpha = 0.6,
                   static = FALSE,
                   palette = viridis::turbo)
```


### [**Guamuchil**]{style="color:#990000"}

```{r heatmap_guamuchil}

z <- z |>
    dplyr::filter(accuracy != "locality")
    

densnv::mp_heatmap(geocoded_datasets = z,
                   cve_edo = "25",
                   locality = "Guamuchil",
                   status_caso = c(1, 2),
                   week = c(1:53),
                   zoom = NULL,
                   map_type = NULL,
                   alpha = 0.6,
                   static = FALSE,
                   palette = viridis::turbo)
```


### [**Escuinapa**]{style="color:#990000"}

```{r heatmap_escuinapa}

z <- z |>
    dplyr::filter(accuracy != "locality")
    

densnv::mp_heatmap(geocoded_datasets = z,
                   cve_edo = "25",
                   locality = "Escuinapa de Hidalgo",
                   status_caso = c(1, 2),
                   week = c(1:53),
                   zoom = NULL,
                   map_type = NULL,
                   alpha = 0.6,
                   static = FALSE,
                   palette = viridis::turbo)
```



:::

